### PR TITLE
travis: deploy on release

### PR DESCRIPTION
**Pull request by vsudilov**
Generated via `travis setup pypi`, which caused some whitespace reformatting on `.travis.yml`.

Not sure what `condition: "${TOX_ENV} == 'cover'" # deploy only once` means in the example @sobolevn provided?

### CODE REVIEW

**Comment by sobolevn** [comment]
The reason behind `condition: "${TOX_ENV} == 'cover'"` is that I only run deploy once in a build.

`travis` creates a job for each entry in `env`. One job for one `tox` target. 
So it will try to deploy after every successful job. Since it is not what I want, I choose `cover` target as the one to deploy stuff.

`travis` misses `after_all_jobs` hooks for a long time...

**Comment by sobolevn** [comment]
Maybe it is a good time to add actual coverage calculation to `cover` target in `tox.ini`?
Right now it does nothing.

Here's an example: https://github.com/sobolevn/django-split-settings/blob/master/tox.ini

Thanks for your efforts! Good job.

**Comment by vsudilov** [comment]
Refactored+simplified the travis.ci

- use nosetests with coverage
- use travis python version support instead of TOX_ENV
- Remove tox from travis-ci.yml

I think this will do what we want -- thoughts?

**Comment by sobolevn** [comment]
Do you want to switch to `nose` from `pytest`? Why? 
`nose` is marked as deprecated. http://nose.readthedocs.io/en/latest/

**Comment by vsudilov** [comment]
Wow, didn't realize that. I picked nose purely because that's what I did in
the past. We should use pytest looks like, sorry about that.

**Comment by sobolevn** [comment]
I guess, that's it!

**Comment by vsudilov** [comment]
cool, want to merge it in then? Or something else needs doing beforehand?

**Comment by sobolevn** [comment]
I don't think there's anything else to do right now. Let's merge and deploy!

**Comment by vsudilov** [comment]
Then please hit the merge button for me (up to you if you want to rebase/squash+merge or not) -- let's not merge in our own PRs.

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
Done!

**Comment by sobolevn** [comment]
So, should we create a PyPI release?

**Pull request merged**
