### PR TITLE
Some changes to support python3

### PR DESCRIPTION
**Pull request by matburt**
In reality dnspython is a bit of a problem also... I have to install dnspython3 after this package to make sure it runs.

### CODE REVIEW

**Comment by vsudilov** [comment]
Neat, thanks for the PR!

I didn't do anything regarding py3 compat, so thanks for the effort towards that. To keep compatibility with py2, how about making something like `if six.PY3: import X as _ \ else: import Y as _`?

If the dnspython is a distinct package in python 3, we'll need to deal with that in `requirements.txt` and/or `setup.py`, too.

**Comment by matburt** [comment]
Totally agree, in eb10bb7 ^^ I just pulled in `six` and use its import as a common point for getting urljoin.  Also make the dnspython or dnspython3 conditional in the setup script.   This works good for me on both python 2.7 and python 3.4

**Comment by matburt** [comment]
The only other thing I can think of is adding some classifiers?   Let me know if you want me to add anything else.

**Comment by jonnybazookatone** [comment]
I guess it would be be great if you could update the travisCI file to run for python3 also.

**Comment by matburt** [comment]
Sounds good, this will be my first foray into Travis CI :)

**Comment by matburt** [comment]
Looks like I have some more work to do here, let me poke at it a bit.

**Comment by matburt** [comment]
I think that'll just about do it, let me know what you think.

**Comment by vsudilov** [comment]
LGTM; Thanks again for the effort!

**Pull request merged**
